name: PureTickets
version: 2.0.0-beta.4
author: broccolai
main: Tickets
api-version: 1.13
commands:
      ticket:
         description: Main command
         aliases: [ti]
         usage: |
           /ticket show - Shows ticket
           /ticket list - Lists tickets
           /ticket create - Creates a ticket
           /ticket done - Done-marks a ticket
           /ticket pick - Picks a ticket
           /ticket yield - Yields a ticket
           /ticket highscore - Shows highscores
permissions:
  tickets.user.close:
    description: "permission for users to close a ticket"
  tickets.user.create:
    description: "permission for users to create a ticket"
  tickets.user.update:
    description: "permission for users to update a ticket"
  tickets.user.reopen:
    description: "permission for users to update a ticket"
  tickets.staff.done:
    description: "permission for staff to done-mark a ticket"
    default: op
  ticket.staff.menu:
    description: "permission for staff to open admin hud"
    default: op
  tickets.staff.pick:
    description: "permission for staff to pick a ticket"
    default: op
  tickets.staff.yield:
    description: "permission for staff to yield a ticket"
    default: op